### ISSUE TITLE
I got a reversed svg, can you check it?

### ISSUE THREAD

**Issue by LawrenceHan** [strongself/MRefresh#1]
let path = "M128 -128h288v288h-288v-288zM480 -128h320v288h-320v-288zM128 224h288v320h-288v-320zM480 224h320v320h-320v-320zM128 608h288v288h-288v-288zM864 -128h320v288h-320v-288zM480 608h320v288h-320v-288zM1248 -128h288v288h-288v-288zM864 224h320v320h-320v-320z M512 1088v288q0 13 -9.5 22.5t-22.5 9.5h-64q-13 0 -22.5 -9.5t-9.5 -22.5v-288q0 -13 9.5 -22.5t22.5 -9.5h64q13 0 22.5 9.5t9.5 22.5zM1248 224h288v320h-288v-320zM864 608h320v288h-320v-288zM1248 608h288v288h-288v-288zM1280 1088v288q0 13 -9.5 22.5t-22.5 9.5h-64 q-13 0 -22.5 -9.5t-9.5 -22.5v-288q0 -13 9.5 -22.5t22.5 -9.5h64q13 0 22.5 9.5t9.5 22.5zM1664 1152v-1280q0 -52 -38 -90t-90 -38h-1408q-52 0 -90 38t-38 90v1280q0 52 38 90t90 38h128v96q0 66 47 113t113 47h64q66 0 113 -47t47 -113v-96h384v96q0 66 47 113t113 47 h64q66 0 113 -47t47 -113v-96h128q52 0 90 -38t38 -90z"

**Comment by mcrakhman** [comment]
As far as I understand the svg coordinate system is the same as the iOS coordinate system (also please see here some examples which are in accordance with my understanding https://developer.mozilla.org/en/docs/Web/SVG/Tutorial/Paths).

 Then lets look at the last path, namely: "M1664 1152v-1280q0 -52 -38 -90t-90 -38h-1408q-52 0 -90 38t-38 90v1280q0 52 38 90t90 38h128v96q0 66 47 113t113 47h64q66 0 113 -47t47 -113v-96h384v96q0 66 47 113t113 47 h64q66 0 113 -47t47 -113v-96h128q52 0 90 -38t38 -90z". 

So the starting point is given in absolute coordinates and it starts at x = 1664, y = 1152, then y decreases by 1280 (in case of our coordinate system that means that we should in fact go from bottom to top, that is exactly what i see when i launch the application). You can try another readers, you should see the same thing.

**Comment by LawrenceHan** [comment]
Thank you for your quick reply, I was using `Font-Awesome` for web svg file, I guess they revered it for purpose. I tried other svg files they works well.
